name: autoresc
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.0.8
  google_sign_in: ^6.0.0
  flutter_font_icons: ^2.2.7
  flutter_staggered_animations: ^1.0.0
  http: ^0.13.0
  flutter_masked_text2: 0.9.1
  image_picker: 1.1.2
  firebase_storage: ^12.1.2
  provider: ^6.1.2
  googleapis: ^8.0.0
  googleapis_auth: ^1.0.0
  mailer: ^6.1.2
  google_ml_kit: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
